#!/bin/bash
# author: Pablo Ordorica
# Description: Bash sript that uses sshfs to extend computer's file directory
# by connecting to the the server specified in the variables below.

USR="pxo2297" #ssh account to ssh into server
DIR="/home/stu12/s15/$USR/" #server directory to mount onto computer
SERVER="cs.rit.edu" #domain of server
MNTPNT="~/RIT/CS" #mount point on computer

#Usage staement
if [ $# -eq 0 ]; then
    echo "Usage: ./mount <host-name>"
else
    #Make Local folders and link them to Student Folders on Server
    if [ "$1" != "stop" ]; then
        #creating mount point
        mkdir -p $MNTPNT
        #clear terminal
        clear
        
        #Try mounting
        echo Linking server directory $USR@$1.$SERVER:$DIR
        if ( sshfs $USR@$1.$SERVER:$DIR $MNTPNT ); then
            echo Connected!
        else 
            echo Mount failed...
        fi
        #Disconnect Drives if stop parameter is passed.
    else
        echo Unmounting server directory
        umount $MNTPNT #unmount directory
    fi
fi
